################################
# Site Settings
################################
lang              : "en"
logo              :
name              : Manuel Bogoni, Ph.D.
title             : Website of Manuel Bogoni
description       : Hydraulic engineer water resources Ph.D.
author            : Manuel Bogoni
email             : manuelbogoni@gmail.com
twitter_username  : ManuelBogoni
linkedin_username : manuelbogoni
github_username   : manuelbogoni
date_format       : "%-d %b %Y"
markdown          : kramdown

################################
# Theme Settings
################################
permalink         : /blog/:year/:month/:day/:title
