################################
# Site Settings
################################
lang              : "en"
logo              :
name              : Manuel Bogoni, Ph.D.
title             : Website of Manuel Bogoni
description       : Hydraulic engineer water resources Ph.D.
date_format       : "%-d %b %Y"
markdown          : kramdown

################################
# My Bio
################################
bio:
  education:
    - year    : "2017"
      title   : "Ph.D."
      detail  : "Hydrodynamics"
      school  : "University of Padova"
    - year    : "2016"
      title   : "Visiting Scholar"
      detail  :
      school  : "Rice University"
    - year    : "2013"
      title   : "M.Sc."
      detail  : "Civil Engineering"
      school  : "University of Padova"
    - year    : "2010"
      title   : "B.Sc."
      detail  : "Civil Engineering"
      school  : "University of Padova"
  experience:
    - year    : "2018-2020"
      title   : "Project engineer"
      detail  :
      company  : "Studio Altieri S.p.A."
    - year    : "2017-2018"
      title   : "Postdoctoral researcher"
      detail  :
      company  : "University of Padova"
    - year    : "2014-2017"
      title   : "Doctoral researcher"
      detail  :

################################
# Site Author
################################
author:
  name             : "Manuel Bogoni"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  email            : manuelbogoni@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:manuelbogoni@gmail.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/manuelbogoni"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/manuelbogoni"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-likedin"
      url: "https://linkedin.com/in/manuelbogoni"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ManuelBogoni"

################################
# Site Footer
################################
footer:
  links:
    - label: "Email"
      icon: "fa fa-envelope-square"
      url: mailto:manuelbogoni@gmail.com
    - label: "Website"
      icon: "fa fa-link"
      # url: "https://your-website.com"
    - label: "Facebook"
      icon: "fa fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "Twitter"
      icon: "fa fa-twitter-square"
      url: "https://twitter.com/manuelbogoni"
    - label: "Instagram"
      icon: "fa fa-instagram"
      url: "https://instagram.com/manuelbogoni"
    - label: "LinkedIn"
      icon: "fa fa-linkedin"
      url: "https://linkedin.com/in/manuelbogoni"
    - label: "GitHub"
      icon: "fa fa-github"
      url: "https://github.com/ManuelBogoni"
    - label: "GitHub"
      icon: "fa fa-github"
      url: "https://github.com/ManuelBogoni"

################################
# Theme Settings
################################
permalink         : /blog/:year/:month/:day/:title

################################
# Output
################################

# Sass/SCSS
sass:
  sass_dir: _scss
  style: compressed
