################################
# DATA
################################
lang              : "en"
logo              :
# url:              : https://github.com/manuelbogoni/manuelbogoni.github.io
# baseurl:          : manuelbogoni.github.io
name              : Manuel Bogoni
nametile          : Manuel Bogoni, Ph.D.
title             : Website of Manuel Bogoni
description       : Hydraulic engineer water resources Ph.D.
date_format       : "%-d %b %Y"

# Build settings
markdown          : kramdown

################################
# NAVIGATION
################################
navigation:
  - url   : "/"
    title : "HOME"
    icon  : "fa fa-home"
  - url   : "/about"
    title : "ABOUT"
    icon  : "fa fa-user-o"
  - url   : "/blog"
    title : "BLOG"
  - url   : "/contact"
    title : "CONTACT"

################################
# MY BIO
################################
bio:
  education:
    - year    : "2017"
      title   : "Ph.D."
      detail  : "Hydrodynamics"
      school  : "University of Padova"
    - year    : "2016"
      title   : "Visiting Scholar"
      detail  :
      school  : "Rice University"
    - year    : "2013"
      title   : "M.Sc."
      detail  : "Civil Engineering"
      school  : "University of Padova"
    - year    : "2010"
      title   : "B.Sc."
      detail  : "Civil Engineering"
      school  : "University of Padova"
  experience:
    - year    : "2018-2020"
      title   : "Project engineer"
      detail  :
      company  : "Studio Altieri S.p.A."
    - year    : "2017-2018"
      title   : "Postdoctoral researcher"
      detail  :
      company  : "University of Padova"
    - year    : "2014-2017"
      title   : "Doctoral researcher"
      detail  :
      company  : "University of Padova"

################################
# SITE AUTHOR
################################
author:
  name             : "Manuel Bogoni"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an **amazing** person."
  location         : "Somewhere"
  email            : manuelbogoni@gmail.com
  links:
    - label: "Email"
      icon: "fa fa-envelope-o"
      url: mailto:manuelbogoni@gmail.com
    - label: "Website"
      icon: "fa fa-link"
      # url: "https://your-website.com"
    - label: "Facebook"
      icon: "fa fa-facebook"
      # url: "https://facebook.com/"
    - label: "Twitter"
      icon: "fa fa-twitter"
      url: "https://twitter.com/manuelbogoni"
    - label: "Instagram"
      icon: "fa fa-instagram"
      url: "https://instagram.com/manuelbogoni"
    - label: "LinkedIn"
      icon: "fa fa-linkedin"
      url: "https://linkedin.com/in/manuelbogoni"
    - label: "GitHub"
      icon: "fa fa-github"
      url: "https://github.com/ManuelBogoni"

################################
# SITE FOOTER
################################
footer:
  links:
    - label: "Email"
      icon: "fa fa-envelope-o"
      url: mailto:manuelbogoni@gmail.com
    - label: "Website"
      icon: "fa fa-link"
      # url: "https://your-website.com"
    - label: "Facebook"
      icon: "fa fa-facebook"
      # url: "https://facebook.com/"
    - label: "Twitter"
      icon: "fa fa-twitter"
      url: "https://twitter.com/manuelbogoni"
    - label: "Instagram"
      icon: "fa fa-instagram"
      url: "https://instagram.com/manuelbogoni"
    - label: "LinkedIn"
      icon: "fa fa-linkedin"
      url: "https://linkedin.com/in/manuelbogoni"
    - label: "GitHub"
      icon: "fa fa-github"
      url: "https://github.com/ManuelBogoni"

################################
# SETTINGS
################################
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

paginate: 2
paginate_path: "/blog/page:num/"

################################
# LAYOUT
################################
sass:
  sass_dir: css/_scss
  style: :compressed

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
